### PR TITLE
macOS fixes (#49)

### PR DESCRIPTION
**Pull request by astraw**
Hi, this PR updates the changes made by @berkus in #49 to v4.2.2.

The git history is messy because I simply merged @berkus' original patch through the git history and kept it working. I'm fine to rewrite the history if requested.

The remaining changes with main could be further cleaned up. In particular, the iOS code looks to me like it won't compile, but I have not tested it. As I did this work already I wanted to leave it here in the hopes it could be merged or could help someone.

### CODE REVIEW

**Comment by astraw** [comment]
Now I fixed the compilation errors on iOS (in 103a0238bb7a7e65b30aba46f2379b6f020e1336 ). There is a test failing on x86_64-apple-darwin which I have not investigated further.

**Comment by eldruin** [comment]
Thank you! This looks fine to me.
There is now only one test failing on `x86_64-apple-darwin`: `test_osx_pty_pair`, though.

**Comment by astraw** [comment]
Yes, I noticed that test, too. I have not dug too deeply but I started to have a look. It will be some days before I can get back to this - if someone wants to jump in, I guess the issue is fairly localized and I'd be grateful. There is various baud_rate handling stuff with various `#[cfg]` compile-time switches which I think must be involved somehow, but I haven't dug deeper.

Actually, I just now noticed that the test also fails on my machine when compiled natively (`aarch64-apple-darwin`) but apparently this test doesn't get run with that architecture in CI.

**Comment by astraw** [comment]
This is superseded by #142.

**Comment by KaSroka** [comment]
Why was this closed? Those changes are still required to make baudrate setting work on M1/2/3 macs.

**Comment by astraw** [comment]
@KaSroka does #142 (released in 4.3.0 AFAIK) fix the issue for you? What problem are you seeing? I was testing on an M1 mac when I made that PR and it Worked For Me. As stated in PR #142, however, I do not understand things deeply enough to know why it resolved my issue, so there could indeed still be something left to resolve.

**Comment by KaSroka** [comment]
I'm still seeing problems with setting the baud rate on my M1 mac on latest version. When I have switched to this PR it worked like a charm. And the only thing I'm changing is the version of serialport crate.

**Comment by astraw** [comment]
Can you please describe the steps to reproduce your problem?

**Comment by sirhcel** [comment]
Thank you for this snippet @KaSroka! I tried to reproduce the issue of the baud rate not being actually used with [`pr49_baud_rate_not_changed.rs`](https://github.com/sirhcel/serialport-rs/commit/3c40d8632d381ffe23782d2cc3209f3ffa459c19), but the baud rate I'm setting appeared on the wire in my setup so far. For example
```
$ cargo run --release --example pr49_baud_rate_not_changed -- /dev/tty.usbserial-112110 19200
```
gives me the expected 19,200 baud on the wire.

I acutally checked the data on the wire with a logic analyzer. I'm running this on an M1 Mac with a SiLabs CP2102N USB serial adapter.

How does your setup looks like? Especialy, which serial adapter are you using? What does `pr49_baud_rate_not_changed.rs` give for results with it?

**Pull request closed without merging**
