### PR TITLE
Add IntoRawHandle impl for FFI ownership transfer

### PR DESCRIPTION
**Pull request by RossSmyth**
Basically the inverse of `FromRawHandle`. Allows an FFI application to take ownership of the handle without leaking a String if constructed on the Rust side.

### CODE REVIEW

**Comment by sirhcel** [comment]
Thank you for this PR! Also providing `IntoRawHandle` looks like the right companion for `AsRawHandle`.

> Allows an FFI application to take ownership of the handle without leaking a String if constructed on the Rust side.

Do you mean leaking [`COMPort::port_name`](https://github.com/serialport/serialport-rs/blob/6bb6d49967ec8e80f7b869e2bc09a75e5b7c6526/src/windows/com.rs#L32) (if present) when `mem::forget`-ting a `COMPort` for not closing it on `drop`?

**Comment by RossSmyth** [comment]
Yeah

**Comment by sirhcel** [comment]
Alright. Thank you! Could you please add a changelog entry for integrating?

**Comment by RossSmyth** [comment]
Done

**Comment by sirhcel** [comment]
Awesome! Thank you very much!

**Pull request merged**
