### PR TITLE
Add bus_id and port_chain field to UsbPortInfo (all platforms)

### PR DESCRIPTION
**Pull request by kindermax**
Add `bus_id` and `port_chain` field to UsbPortInfo (all platforms)

Implementation taken and adapted from `nusb` crate

### CODE REVIEW

**Comment by sirhcel** [comment]
Thank you for starting this PR! We've currently got a (CI) issue with one of our sub dependency which is about getting resolved with #229 and #230. So rebasing the changes on #230 will resolve the red herrings arising from #229 in the CI builds here as well.

Have you completely abandoned this idea or are you still working on it in https://github.com/kindermax/serialport-rs/pull/1? In case you are, do you know if there is a cross-platform string representation of a port "path"?

**Comment by sirhcel** [comment]
Have you seen the reference to the nusb crate regarding port chains #222? They seem to use a binary representation. Do you see a big plus for either a string representation or a vector of port numbers?

I have not looked into it but using nusb for determining bus ID and port chain might also be an option.

**Comment by kindermax** [comment]
Hi, @sirhcel, I am still working on this functionality, I just mistakenly opened PR to the original repo instead of my fork, because the work wasn't ready to be shown here yet. But, anyway)

In general, I tried to implement this functionality as close as possible to `nusb` to be able to share the same location representation between `nusb` part of a program and `serialport-rs` part of a program.

**Comment by kindermax** [comment]
> I have not looked into it but using nusb for determining bus ID and port chain might also be an option.
Theoretically this is possible, if somehow match `nusb::DeviceInfo` with `SerialPortType::UsbPort(UsbPortInfo)` then we indeed can use port info from `nusb`, but I went in other direction and end up with this PR)

**Comment by kindermax** [comment]
Reopened PR

**Pull request closed without merging**
